package de.bbshaarentor.zeiterfassung.ui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreeCellRenderer;
import javax.swing.tree.TreeSelectionModel;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import de.bbshaarentor.zeiterfassung.projekte.Projekt;
import de.bbshaarentor.zeiterfassung.projekte.ProjektBereich;
import de.bbshaarentor.zeiterfassung.projekte.ProjektContainer;
import de.bbshaarentor.zeiterfassung.projekte.ZeitErfassung;
import de.bbshaarentor.zeiterfassung.ui.models.ProjekteTreeModel;

public class MainView implements ZeitErfassungsUIPanel {

    private JTree projektJTree;
    private JSplitPane splitPane;
    private JPanel mainPanel;
    private JButton neuesProjektButton;
    private JButton neuerBenutzer;
    private final ProjektContainer projektContainer;

    public MainView(ProjektContainer projektContainer) {

        this.projektContainer = projektContainer;

        ProjekteTreeModel projekteTreeModel = new ProjekteTreeModel(this.projektContainer);
        this.projektJTree.setModel(projekteTreeModel);

        this.projektJTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);

        TreeCellRenderer cellRenderer = this.projektJTree.getCellRenderer();
        this.projektJTree.setCellRenderer((tree, value, selected, expanded, leaf, row, hasFocus) -> {

            String text = "";
            if (value instanceof Projekt) {
                text = ((Projekt) value).getBezeichnung();
            } else if (value instanceof ProjektBereich) {
                text = ((ProjektBereich) value).getBezeichnung();
            } else if (value instanceof ZeitErfassung) {
                text = ((ZeitErfassung) value).getId() + ": ";
            } else {
                text = value.toString();
            }

            /*
             * Hier wird etwas geschummelt, da wir einen Ordentlichen Text
             * in der Oberfläche haben möchten übernehmen wir hier das Design
             * des Orignal Renderers aber geben unseren Anzeige Namen an.
             */
            Component component = cellRenderer.getTreeCellRendererComponent(tree, text, selected, expanded, leaf, row, hasFocus);
            return component;
        });

        this.projektJTree.addTreeSelectionListener(new TreeSelectionListener() {
            @Override
            public void valueChanged(TreeSelectionEvent e) {

                Object[] objects = e.getPath().getPath();
                Object untersteAuswahl = objects[objects.length - 1];

                if (untersteAuswahl instanceof ZeitErfassung) {
                    MainView.this.splitPane.setRightComponent(new ZeitErfassenForm((ZeitErfassung) untersteAuswahl).getMainPanel());
                } else if (untersteAuswahl instanceof Projekt) {
                    MainView.this.splitPane.setRightComponent(new ProjektZusammenFassung((Projekt) untersteAuswahl, projektContainer).getMainPanel());
                } else {
                    MainView.this.splitPane.setRightComponent(new JPanel());
                }

            }
        });

        this.neuesProjektButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JDialog jDialog = new NeuesProjektDialog(projektContainer, null);
                jDialog.setTitle("Neues Projekt:");
                jDialog.setSize(320, 130);
                jDialog.setVisible(true);
            }
        });

        this.neuerBenutzer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JDialog jDialog = new BenutzerAnlegenDialog(projektContainer);
                jDialog.setTitle("Neuen Benutzer anlegen");
                jDialog.setSize(320, 130);
                jDialog.setVisible(true);
            }
        });
    }

    @Override
    public JPanel getMainPanel() {
        return this.mainPanel;
    }

    public void ladeFormInRechteSplitpane(ZeitErfassungsUIPanel zeitErfassungsUIPanel) {
        this.splitPane.setRightComponent(zeitErfassungsUIPanel.getMainPanel());
    }

    // @formatter:off

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        this.$$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        mainPanel.add(toolBar1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        neuesProjektButton = new JButton();
        neuesProjektButton.setMaximumSize(new Dimension(107, 20));
        neuesProjektButton.setMinimumSize(new Dimension(107, 20));
        neuesProjektButton.setPreferredSize(new Dimension(107, 20));
        neuesProjektButton.setText("Neues Projekt");
        toolBar1.add(neuesProjektButton);
        neuerBenutzer = new JButton();
        neuerBenutzer.setMaximumSize(new Dimension(107, 20));
        neuerBenutzer.setMinimumSize(new Dimension(107, 20));
        neuerBenutzer.setPreferredSize(new Dimension(107, 20));
        neuerBenutzer.setText("Neuer Benutzer");
        toolBar1.add(neuerBenutzer);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 10, 10, 10), -1, -1));
        mainPanel.add(panel1,
                new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        splitPane = new JSplitPane();
        splitPane.setDividerLocation(175);
        splitPane.setOneTouchExpandable(true);
        panel1.add(splitPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null,
                new Dimension(500, 500), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        splitPane.setRightComponent(panel2);
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane.setLeftComponent(scrollPane1);
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "Projekte", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        projektJTree = new JTree();
        projektJTree.setRootVisible(false);
        projektJTree.putClientProperty("JTree.lineStyle", "");
        scrollPane1.setViewportView(projektJTree);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
