package de.bbshaarentor.zeiterfassung.ui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import de.bbshaarentor.zeiterfassung.ProjektZeiterfassungMain;
import de.bbshaarentor.zeiterfassung.projekte.ProjektBereich;
import de.bbshaarentor.zeiterfassung.projekte.ProjektContainer;

public class ProjektBereichZusammenfassen implements ZeitErfassungsUIPanel {

    private final ProjektContainer projektContainer;
    private final ProjektBereich projektBereich;
    private JLabel projektBereichName;
    private JButton neueZeiterfassungButton;
    private JPanel mainPanel;

    public ProjektBereichZusammenfassen(ProjektContainer projektContainer, ProjektBereich projektBereich) {

        this.projektContainer = projektContainer;
        this.projektBereich = projektBereich;

        this.projektBereichName.setText("Projekt Bereich: " + projektBereich.getBezeichnung());

        this.neueZeiterfassungButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    JDialog jDialog = new ZeitErfassenDialog(projektContainer, projektBereich);
                    jDialog.setTitle("Neue Zeiterfassung:");
                    jDialog.setSize(400, 300);
                    jDialog.setVisible(true);

                } catch (Exception exception) {
                    ProjektZeiterfassungMain.showFehlerDialog(exception);
                }
            }
        });
    }

    @Override
    public JPanel getMainPanel() {
        return this.mainPanel;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        this.$$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        projektBereichName = new JLabel();
        projektBereichName.setText("Label");
        mainPanel.add(projektBereichName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1,
                new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        neueZeiterfassungButton = new JButton();
        neueZeiterfassungButton.setText("Neue Zeiterfassung");
        mainPanel.add(neueZeiterfassungButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
