package de.bbshaarentor.zeiterfassung.ui;

import java.awt.*;

import javax.swing.*;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import de.bbshaarentor.zeiterfassung.projekte.Projekt;
import de.bbshaarentor.zeiterfassung.projekte.ProjektContainer;

public class ProjektZusammenFassung implements ZeitErfassungsUIPanel {

    private final Projekt projekt;
    private final ProjektContainer projektContainer;

    private JLabel projektNameLabel;
    private JButton neuenProjektbereichAnlegenButton;
    private JPanel mainPanel;

    public ProjektZusammenFassung(Projekt projekt, ProjektContainer projektContainer) {

        this.projekt = projekt;
        this.projektContainer = projektContainer;

        this.projektNameLabel.setText(projekt.getBezeichnung());

        this.neuenProjektbereichAnlegenButton.addActionListener(e -> {
            JDialog jDialog = new NeuesProjektDialog(projektContainer, projekt);
            jDialog.setTitle("Neuer Projektbereich:");
            jDialog.setSize(320, 130);
            jDialog.setVisible(true);
        });
    }

    @Override
    public JPanel getMainPanel() {
        return this.mainPanel;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        this.$$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        projektNameLabel = new JLabel();
        projektNameLabel.setText("Label");
        mainPanel.add(projektNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        neuenProjektbereichAnlegenButton = new JButton();
        neuenProjektbereichAnlegenButton.setText("Neuen Projektbereich anlegen");
        mainPanel.add(neuenProjektbereichAnlegenButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1,
                new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
