package de.bbshaarentor.zeiterfassung.ui;

import java.awt.*;

import javax.swing.*;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import de.bbshaarentor.zeiterfassung.User;
import de.bbshaarentor.zeiterfassung.projekte.ZeitErfassung;

public class ZeitErfassenForm implements ZeitErfassungsUIPanel {
    private JTextArea kommentarTextArea;
    private JButton speichernButton;
    private JComboBox benutzerComboBox;
    private JPanel mainPanel;

    public ZeitErfassenForm(ZeitErfassung zeitErfassung) {

        this();

        User benutzer = zeitErfassung.getBenutzer();
        this.benutzerComboBox.addItem(benutzer);
        this.benutzerComboBox.setSelectedItem(benutzer);
        this.kommentarTextArea.setText(zeitErfassung.getKommentar());

        this.benutzerComboBox.setEnabled(false);
        this.kommentarTextArea.setEnabled(false);
        this.speichernButton.setEnabled(false);
    }

    public ZeitErfassenForm() {

        this.benutzerComboBox.setRenderer(new ListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

                String text;
                if (value instanceof User) {
                    text = ((User) value).getName();
                } else if (value == null) {
                    text = "";
                } else {
                    text = value.toString();
                }

                return new JLabel(text);
            }
        });
    }

    @Override
    public JPanel getMainPanel() {
        return this.mainPanel;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        this.$$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        kommentarTextArea = new JTextArea();
        mainPanel.add(kommentarTextArea, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Benutzer:");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 16), null, 0, false));
        speichernButton = new JButton();
        speichernButton.setText("Speichern");
        mainPanel.add(speichernButton, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        benutzerComboBox = new JComboBox();
        mainPanel.add(benutzerComboBox, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
